name: 'Notion github catalog'
description: 'A github action that synchronises a Github repo data, including Backstage definition file information, with a Notion database'
branding:
  icon: git-pull-request
  color: blue
inputs:
  github_owner:
    description: 'Github owner organization or user - e.g. infinitaslearning'
    required: true    
  github_token:
    description: 'Github API token'
    required: true    
  notion_token:
    description: 'Notion API token'
    required: true    
  database:
    description: 'Parent database to add to'
    required: true
  push_missing:
    description: 'Push services that miss a `catalog-info.yaml` file or not'
    required: true
  ignore_hash:
    description: 'Ignore the hash and update regardless'    
    default: 'false'
  system_database:
    description: 'Database ID to read systems from'    
  owner_database:
    description: 'Database ID to read segments from'    
  repository_type:
    description: 'Github repository type (e.g. all|private|internal), defaults to `all`' 
    default: 'all'
  repository_filter:
    description: 'Regex string to filter repository name by, defaults to .*' 
    default: '.*'
  repository_batch_size:
    description: 'How many github repos to request in parallel, defaults to 10'   
    default: '10'
  catalog_file:
    description: 'Catalog file name to look for in the root of repo, defaults to `catalog-file.yaml`' 
    default: 'catalog-info.yaml'
outputs:
  status: 
    description: 'The status of the scan'
runs:
  using: 'node16'
  main: 'dist/index.js'
