name: 'Notion github catalog'
description: 'A github action that synchronises a Github repo data, including Backstage definition file information, with a Notion database'
branding:
  icon: git-pull-request
  color: blue
inputs:
  github_owner:
    description: 'Github owner organization or user - e.g. infinitaslearning'
    required: true    
  github_token:
    description: 'Github API token'
    required: true    
  notion_token:
    description: 'Notion API token'
    required: true    
  database:
    description: 'Parent database to add to'
    required: true
  system_database:
    description: 'Database ID to read systems from'    
  owner_database:
    description: 'Database ID to read segments from'    
  repository_type:
    description: 'Github repository type (e.g. all|private|internal), defaults to `all`' 
  repository_filter:
    description: 'Regex string to filter repository name by, defaults to .*' 
  catalog_file:
    description: 'Catalog file name to look for in the root of repo, defaults to `catalog_file.yaml`' 
outputs:
  status: 
    description: 'The status of the scan'
runs:
  using: 'node16'
  main: 'dist/index.js'
